### ISSUE TITLE
Configuration option for font size (Web UI)

### ISSUE THREAD

**Issue by japa-fi** [jlesage/docker-czkawka#24]
### Idea

What I'm after is a simple way to increase the webUI font size. Currently with my browser in full screen mode, the font is unbearable small. 
(I didn't find font size mentioned on current documentation)

Ps. Nice prog

**Comment by jlesage** [comment]
Is the font small because the resolution of the app is very high ?  What kind of scaling did you set ?

**Comment by japa-fi** [comment]
DOH! (Insert Homer Simpson emoji here)
Didn't realize that the resolution settings also affect the Web UI font size.

You might consider adding adding: "Higher resolution results to smaller font size and vice versa." to DISPLAY_WIDTH and DISPLAY_HEIGHT environment variable descriptions.

**Comment by jlesage** [comment]
To clarify, higher resolution doesn't result in smaller font size.  However, if you chose the "local scaling", the application's screen is downscaled to fit your browser's window size.  Selecting "remote sizing" might be a better choice, since the application's screen resolution is adjusted to your browser's window, resulting in a 1:1 scaling.
